<html><head><title>Mover::Date::Navigation</title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" >

<style type="text/css">
 <!--/*--><![CDATA[/*><!--*/
BODY {
  background: white;
  color: black;
  font-family: arial,sans-serif;
  margin: 0;
  padding: 1ex;
}

A:link, A:visited {
  background: transparent;
  color: #006699;
}

A[href="#POD_ERRORS"] {
  background: transparent;
  color: #FF0000;
}

DIV {
  border-width: 0;
}

DT {
  margin-top: 1em;
  margin-left: 1em;
}

.pod { margin-right: 20ex; }

.pod PRE     {
  background: #eeeeee;
  border: 1px solid #888888;
  color: black;
  padding: 1em;
  white-space: pre;
}

.pod H1      {
  background: transparent;
  color: #006699;
  font-size: large;
}

.pod H1 A { text-decoration: none; }
.pod H2 A { text-decoration: none; }
.pod H3 A { text-decoration: none; }
.pod H4 A { text-decoration: none; }

.pod H2      {
  background: transparent;
  color: #006699;
  font-size: medium;
}

.pod H3      {
  background: transparent;
  color: #006699;
  font-size: medium;
  font-style: italic;
}

.pod H4      {
  background: transparent;
  color: #006699;
  font-size: medium;
  font-weight: normal;
}

.pod IMG     {
  vertical-align: top;
}

.pod .toc A  {
  text-decoration: none;
}

.pod .toc LI {
  line-height: 1.2em;
  list-style-type: none;
}

  /*]]>*/-->
</style>


</head>
<body class='pod'>
<!--
  generated by Pod::Simple::HTML v3.16,
  using Pod::Simple::PullParser v3.16,
  under Perl v5.014002 at Sun Mar 17 17:05:26 2013 GMT.

 If you want to change this HTML document, you probably shouldn't do that
   by changing it directly.  Instead, see about changing the calling options
   to Pod::Simple::HTML, and/or subclassing Pod::Simple::HTML,
   then reconverting this document from the Pod source.
   When in doubt, email the author of Pod::Simple::HTML for advice.
   See 'perldoc Pod::Simple::HTML' for more info.

-->

<!-- start doc -->
<a name='___top' class='dummyTopAnchor' ></a>

<div class='indexgroup'>
<ul   class='indexList indexList1'>
  <li class='indexItem indexItem1'><a href='#NAME'>NAME</a>
  <li class='indexItem indexItem1'><a href='#VERSION'>VERSION</a>
  <li class='indexItem indexItem1'><a href='#SYNOPSIS'>SYNOPSIS</a>
  <ul   class='indexList indexList2'>
    <li class='indexItem indexItem2'><a href='#Include_role_Convert%3A%3AInput%3A%3ATo%3A%3ADateTime_to_convert_input_in_any_format_to_a_DateTime_date_object.'>Include role Convert::Input::To::DateTime to convert input in any format to a DateTime date object.</a>
    <li class='indexItem indexItem2'><a href='#date_unit_String_to_represent_date_units%2C_year%2C_month%2C_week%2C_day%2C_hour%2C_minute._Is_a_%27rw%27_attribute.'>date_unit String to represent date units, year, month, week, day, hour, minute. Is a &#39;rw&#39; attribute.</a>
    <li class='indexItem indexItem2'><a href='#delta_date_units_Number_of_days_before_or_after_a_specific_base_date_Defaults_to_0._Is_a_%27rw%27_attribute.'>delta_date_units Number of days before or after a specific base date Defaults to 0. Is a &#39;rw&#39; attribute.</a>
    <li class='indexItem indexItem2'><a href='#base_tz_The_time_zone_for_the_base_date._Defaults_to_%27UTC%27_Is_a_%27rw%27_attribute.'>base_tz The time zone for the base_date. Defaults to &#39;UTC&#39; Is a &#39;rw&#39; attribute.</a>
    <li class='indexItem indexItem2'><a href='#get_now_dt_Create_a_DateTime_object_with_time_zone_set_to_the_base_time_zone._my_%24MoverNowDt_%3D_%24MoverDate-%3Eget_now_dt()%3B'>get_now_dt Create a DateTime object with time zone set to the base time zone. my $MoverNowDt = $MoverDate-&#62;get_now_dt();</a>
  </ul>
  <li class='indexItem indexItem1'><a href='#NAME'>NAME</a>
  <li class='indexItem indexItem1'><a href='#DESCRIPTION_Used_to_get_dates%2C_date_ranges_in_the_future_or_past%2C_relative_to_a_given_base_date.'>DESCRIPTION Used to get dates, date ranges in the future or past, relative to a given base date.</a>
  <li class='indexItem indexItem1'><a href='#AUTHOR'>AUTHOR</a>
  <li class='indexItem indexItem1'><a href='#VERSION'>VERSION</a>
  <li class='indexItem indexItem1'><a href='#SEE_ALSO'>SEE ALSO</a>
  <li class='indexItem indexItem1'><a href='#AUTHOR'>AUTHOR</a>
  <li class='indexItem indexItem1'><a href='#COPYRIGHT_AND_LICENSE'>COPYRIGHT AND LICENSE</a>
</ul>
</div>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="NAME"
>NAME</a></h1>

<p>Mover::Date::Navigation - Mover Date Navigation</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="VERSION"
>VERSION</a></h1>

<p>version 0.001</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="SYNOPSIS"
>SYNOPSIS</a></h1>

<pre> use Mover::Date::Navigation;  # To traverse across Movers Dates and Times

 The the attributes can be sent as named paramaters or as a single HashRef
 with all the elements.

 my $MoverDateNav = Mover::Date::Navigation-&#62;new(
    date_unit        =&#62; $date_unit,  # year|month|week|day|hour|minute
    delta_date_units =&#62; $int,        # Number of $date_unit&#39;s from base_date
    before_or_after  =&#62; $before_or_after,  # q/after|before/
    base_date        =&#62; $base_date # DateTime, yyyymmdd mmddyyyy, ddmmyyyy,
                                     ISO-1860 or even NaturalDateTime format)
    base_tz          =&#62; q/UTC/    # This is the default
 ); 

 #--Get the start and end DateTime Objects or the selected range

 my ($FirstDateTime, $LastDateTime )= @{$MoverDateNav-&#62;get_date_range()};


 #--- Where we can go next relative to the current position

 my ( $prev_params, $next_params ) =
      $MoverDateNav-&#62;get_previous_and_next_date_range_params();

 #    $prev_params = {
 #        date_unit        =&#62; $self-&#62;date_unit(),
 #        delta_date_units =&#62; 1,
 #        before_or_after  =&#62; q/before/,
 #        base_date        =&#62; 2013-09-12T12:24:22
 #    };

 #    $next_params = {
 #        date_unit        =&#62; $self-&#62;date_unit(),
 #        delta_date_units =&#62; 1,
 #        before_or_after  =&#62; q/after/,
 #        base_date        =&#62; 2013-09-12T12:24:22
 #    };</pre>

<h2><a class='u' href='#___top' title='click to go to top of document'
name="Include_role_Convert::Input::To::DateTime_to_convert_input_in_any_format_to_a_DateTime_date_object."
>Include role Convert::Input::To::DateTime to convert input in any format to a DateTime date object.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'
name="date_unit_String_to_represent_date_units,_year,_month,_week,_day,_hour,_minute._Is_a_&#39;rw&#39;_attribute."
>date_unit String to represent date units, year, month, week, day, hour, minute. Is a &#39;rw&#39; attribute.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'
name="delta_date_units_Number_of_days_before_or_after_a_specific_base_date_Defaults_to_0._Is_a_&#39;rw&#39;_attribute."
>delta_date_units Number of days before or after a specific base date Defaults to 0. Is a &#39;rw&#39; attribute.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'

>before_or_after String to represent before_or_after a particular date. q/before/ or q/after/. Defaults to q/after/. Is a &#39;rw&#39; attribute.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'

>base_date Starting point for the date navigation. MoverDateTimeHref object. Uses role Convert::Input::To::DateTime to convert input to a DateTime object which is then converted to a DateTime hashref.. It will accept and coerce a date in String, HashRef or DateTime format. This is a &#39;rw&#39; attribute.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'
name="base_tz_The_time_zone_for_the_base_date._Defaults_to_&#39;UTC&#39;_Is_a_&#39;rw&#39;_attribute."
>base_tz The time zone for the base_date. Defaults to &#39;UTC&#39; Is a &#39;rw&#39; attribute.</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'
name="get_now_dt_Create_a_DateTime_object_with_time_zone_set_to_the_base_time_zone._my_$MoverNowDt_=_$MoverDate-&#62;get_now_dt();"
>get_now_dt Create a DateTime object with time zone set to the base time zone. my $MoverNowDt = $MoverDate-&#62;get_now_dt();</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'

>get_delta_datetime Returns a DateTime Object which is delta_date_units before_or_after a given base_date or DateTime-&#62;now(). Assumes that all the required Mover::Date::Navigation Attributes are properly set. (Maybe thats too big of an assumption.)</a></h2>

<pre> my $FutureDate = $MoverNav-&#62;get_delta_datetime();</pre>

<h2><a class='u' href='#___top' title='click to go to top of document'

>get_date_range Returns an array ref of two DateTime objects, one for the start and one end of the requested date_period(year, month, week). For day, hour or minute, only one truncated DateTime object will be included in the returned ArrayRef.</a></h2>

<pre> my $date_range_arr =  $MoverDateNav-&#62;get_date_range();</pre>

<h2><a class='u' href='#___top' title='click to go to top of document'

>get_previous_and_next_date_range_params Having got the relevant date range, now set up the parameters for the date range before and after the current date range. This will make it easier for the requesting application to create links to the previous and next time periods. Returns an array with two hash refs (\%prev_params, \%next_params). my @prev_and_next_params = $MoverDate-&#62;get_previous_and_next_date_range_params();</a></h2>

<h2><a class='u' href='#___top' title='click to go to top of document'

>around qw/ get_date_range get_delta_datetime / Validate the calling parameters of these date navigation methods. If the BaseDate is in DateTime format, use the cloned DateTime version. If the BaseDate is not in DateTime format, then convert from whatever date format to DateTime or else get DateTime now.</a></h2>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="NAME"
>NAME</a></h1>

<p>Mover::Date::Navigation - Moose Object For Traversing Across Dates And Times</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="DESCRIPTION_Used_to_get_dates,_date_ranges_in_the_future_or_past,_relative_to_a_given_base_date."
>DESCRIPTION Used to get dates, date ranges in the future or past, relative to a given base date.</a></h1>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="AUTHOR"
>AUTHOR</a></h1>

<p>austin,,,</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="VERSION"
>VERSION</a></h1>

<p>Version 0.01</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="SEE_ALSO"
>SEE ALSO</a></h1>

<ul>
<li>
<pre> L&#60;Convert::Input::To::DateTime&#62;</pre>
</li>

<li>
<pre> L&#60;MooseX::Types&#62;</pre>
</li>

<li>
<pre> L&#60;DateTime&#62;</pre>
</li>

<li>
<pre> L&#60;Mover::Date::Types&#62;</pre>
</li>

<li>
<pre> L&#60;Mover.pm&#62;</pre>
</li>
</ul>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="AUTHOR"
>AUTHOR</a></h1>

<p>Austin Kenny &#60;aibistin.cionnaith@gmail.com&#62;</p>

<h1><a class='u' href='#___top' title='click to go to top of document'
name="COPYRIGHT_AND_LICENSE"
>COPYRIGHT AND LICENSE</a></h1>

<p>This software is copyright (c) 2013 by Austin Kenny.</p>

<p>This is free software; you can redistribute it and/or modify it under the same terms as the Perl 5 programming language system itself.</p>

<!-- end doc -->

</body></html>
